### ISSUE TITLE
windows端的搭建教程？

### ISSUE THREAD

**Issue by kknd222** [bigbaser/TcloudServer#13]
RT
有木有windows端的搭建教程？

**Comment by vissssa** [comment]
不建议在windows上部署，如果一定要的话，最好参考https://github.com/bigbaser/TcloudServer/wiki/Docker%E9%83%A8%E7%BD%B2
在windows的docker上运行

**Comment by kknd222** [comment]
了解，多谢！
感觉这个很不错
