### ISSUE TITLE
docker部署找不到snapshot_2.json这个文件

### ISSUE THREAD

**Issue by MaxGuo** [bigbaser/TcloudServer#44]
找不到snapshot_2.json这个文件

**Comment by tsbxmw** [comment]
https://github.com/bigbaser/TcloudServer/blob/master/deploy/docs/Docker%E9%83%A8%E7%BD%B2.md

**Comment by tsbxmw** [comment]
> 请查看最新的文档。

> 下面是最新的文件：

[文件地址](https://github.com/bigbaser/TcloudServer/blob/master/deploy/kong.json)
